
--Create "CURATED" database 
USE ROLE "{{ENVIRONMENT}}_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "{{ENVIRONMENT}}_CURATED_DB";
ALTER DATABASE "{{ENVIRONMENT}}_CURATED_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;