USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "DEV_SYSADMIN";
GRANT ROLE "DEV_SYSADMIN" TO ROLE SYSADMIN;


USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "DEV_SYSADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "DEV_SYSADMIN";   