--
-- DEV Environment
--

USE ROLE "DEV_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "DEV_CURATED_DB";
ALTER DATABASE "DEV_CURATED_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;
CREATE DATABASE IF NOT EXISTS "DEV_RAW_DB";
ALTER DATABASE "DEV_RAW_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;
CREATE SCHEMA IF NOT EXISTS "DEV_RAW_DB"."TELEMATICS";
ALTER SCHEMA "DEV_RAW_DB"."TELEMATICS" SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE DATABASE IF NOT EXISTS "DEV_REFINED_DB";
ALTER DATABASE "DEV_REFINED_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;

USE ROLE "DEV_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "DEV_COMMON_DB";
ALTER DATABASE "DEV_COMMON_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;

USE ROLE "DEV_SYSADMIN";
CREATE TRANSIENT DATABASE IF NOT EXISTS "SANDBOX_DB";
ALTER DATABASE "SANDBOX_DB" SET DATA_RETENTION_TIME_IN_DAYS = 1;
CREATE TRANSIENT SCHEMA IF NOT EXISTS "SANDBOX_DB"."VENU";
ALTER SCHEMA "SANDBOX_DB"."VENU" SET DATA_RETENTION_TIME_IN_DAYS = 1;




