
--Create "REFINED" database 
USE ROLE "{{ENVIRONMENT}}_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "{{ENVIRONMENT}}_REFINED_DB";
ALTER DATABASE "{{ENVIRONMENT}}_REFINED_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;