
--Create "OUTBOUND" database 
USE ROLE "{{ENVIRONMENT}}_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "{{ENVIRONMENT}}_OUTBOUND_DB";
ALTER DATABASE "{{ENVIRONMENT}}_OUTBOUND_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;