
--Create "COMMON" database 
USE ROLE "{{ENVIRONMENT}}_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "{{ENVIRONMENT}}_COMMON_DB";
ALTER DATABASE "{{ENVIRONMENT}}_COMMON_DB" SET DATA_RETENTION_TIME_IN_DAYS = 8;






