--Create environment default role and grant to SYSADMIN
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "{{ENVIRONMENT}}_SYSADMIN";
GRANT ROLE "{{ENVIRONMENT}}_SYSADMIN" TO ROLE SYSADMIN;

--Grant privileges to default role
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "{{ENVIRONMENT}}_SYSADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "{{ENVIRONMENT}}_SYSADMIN";

BEGIN
  IF "{{ENVIRONMENT}}" = "QA" OR "{{ENVIRONMENT}}" = "PROD" THEN
    USE ROLE USERADMIN;
        CREATE ROLE IF NOT EXISTS "{{ENVIRONMENT}}_BUSINESS_FR";
        GRANT ROLE "{{ENVIRONMENT}}_BUSINESS_FR" TO ROLE SYSADMIN;
  ELSE
    END IF
END;


-- BEGIN
--   LET count := {{CONDITION}};
--   IF (count = 0)  THEN
--     USE ROLE USERADMIN;
--     CREATE ROLE IF NOT EXISTS "{{ENVIRONMENT}}_AZURE_FR";   
--   END IF;
-- END; 
