config-version: 1
ENVIRONMENT: SNOWFLAKE-IAC-QA
snowflake-account: 'lo27224.ap-southeast-1'
snowflake-database: 'BASE_DB'
snowflake-role: 'ACCOUNTADMIN'
snowflake-user: 'artisingh'
snowflake-warehouse: 'COMPUTE_WH'
root-folder: 'migrations'
change-history-table: 'BASE_DB.SCHEMACHANGE.CHANGE_HISTORY'
create-change-history-table: true
modules-folder: 'modules'
vars:
  ENVIRONMENT: 'QA'
  CONDITION: '1'

